
import React from 'react';
import { useQuery } from '@tanstack/react-query';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { supabase } from '@/integrations/supabase/client';
import { FileText, Bot, User, AlertCircle } from 'lucide-react';

export function DraftViewerTab() {
  const { data: proposals, isLoading } = useQuery({
    queryKey: ['proposals-with-answers'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('proposals')
        .select(`
          *,
          sections (
            *,
            questions (
              *,
              answers (*),
              clarifications (*)
            )
          )
        `)
        .order('created_at', { ascending: false });
      
      if (error) throw error;
      return data;
    }
  });

  if (isLoading) {
    return <div>Loading drafts...</div>;
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h2 className="text-2xl font-bold">Draft Proposals</h2>
        <Button>
          <FileText className="mr-2 h-4 w-4" />
          Export All Drafts
        </Button>
      </div>

      {proposals?.map((proposal) => (
        <Card key={proposal.id}>
          <CardHeader>
            <div className="flex items-start justify-between">
              <div>
                <CardTitle>{proposal.title}</CardTitle>
                <CardDescription>
                  Client: {proposal.client_name} • Status: {proposal.status}
                </CardDescription>
              </div>
              <Badge variant="outline">
                {proposal.sections?.reduce((total, section) => 
                  total + (section.questions?.length || 0), 0
                )} questions
              </Badge>
            </div>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {proposal.sections?.map((section) => (
                <div key={section.id} className="border rounded-lg p-4">
                  <h3 className="font-medium text-lg mb-3">{section.title}</h3>
                  <div className="space-y-3">
                    {section.questions?.map((question) => {
                      const hasAnswer = question.answers && question.answers.length > 0;
                      const needsClarification = question.clarification_required && 
                        (!question.clarifications || 
                         !question.clarifications.some(c => c.status === 'answered'));

                      return (
                        <div key={question.id} className="border-l-4 border-gray-200 pl-4">
                          <div className="flex items-start justify-between mb-2">
                            <p className="font-medium text-gray-900">{question.question_text}</p>
                            <div className="flex items-center space-x-2">
                              {needsClarification && (
                                <Badge variant="outline" className="bg-yellow-50 text-yellow-700">
                                  <AlertCircle className="mr-1 h-3 w-3" />
                                  Needs Clarification
                                </Badge>
                              )}
                              {hasAnswer && (
                                <Badge variant="outline" className="bg-blue-50 text-blue-700">
                                  <Bot className="mr-1 h-3 w-3" />
                                  AI Drafted
                                </Badge>
                              )}
                              {question.requires_review && (
                                <Badge variant="outline" className="bg-orange-50 text-orange-700">
                                  <User className="mr-1 h-3 w-3" />
                                  Needs Review
                                </Badge>
                              )}
                            </div>
                          </div>
                          
                          {hasAnswer ? (
                            <div className="bg-gray-50 p-3 rounded-lg">
                              <p className="text-gray-700">
                                {question.answers[0].answer_text}
                              </p>
                              <div className="mt-2 text-xs text-gray-500">
                                Generated by {question.answers[0].generated_by} • 
                                Version {question.answers[0].version_number}
                              </div>
                            </div>
                          ) : needsClarification ? (
                            <div className="bg-yellow-50 p-3 rounded-lg">
                              <p className="text-yellow-800">
                                This question needs clarification before AI can draft a response.
                              </p>
                            </div>
                          ) : (
                            <div className="bg-gray-50 p-3 rounded-lg">
                              <p className="text-gray-500 italic">
                                No draft available yet. ContentAgent will generate this once clarifications are complete.
                              </p>
                            </div>
                          )}
                        </div>
                      );
                    })}
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      ))}

      {proposals?.length === 0 && (
        <Card>
          <CardContent className="text-center py-12">
            <FileText className="mx-auto h-12 w-12 text-gray-400" />
            <h3 className="mt-4 text-lg font-medium">No proposals yet</h3>
            <p className="text-gray-500">Upload an RFP to start creating draft responses</p>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
