// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwqltdwttzfrnmxmwkyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3cWx0ZHd0dHpmcm5teG13a3lqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNjYwMDEsImV4cCI6MjA2NDc0MjAwMX0.bjI8En6dcmGNK6OO0-lnoM0Bz-2WIzoozXjUyNIbriY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);